[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bayesapiwrapper"
version = "0.1.3"
authors = [
  { name="ArbolitoLoco", email="arbolitoloco1@protonmail.com" },
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"